//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISRC.Web.T_Dept {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtID;
		protected global::System.Web.UI.WebControls.TextBox txtName;
		protected global::System.Web.UI.WebControls.TextBox txtQuality;
		protected global::System.Web.UI.WebControls.TextBox txtRegionID;
		protected global::System.Web.UI.WebControls.TextBox txtContactor;
		protected global::System.Web.UI.WebControls.TextBox txtTel;
		protected global::System.Web.UI.WebControls.TextBox txtOderID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
