//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISRC.Web.T_Dept {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblName;
	protected global::System.Web.UI.WebControls.Label lblQuality;
	protected global::System.Web.UI.WebControls.Label lblRegionID;
	protected global::System.Web.UI.WebControls.Label lblContactor;
	protected global::System.Web.UI.WebControls.Label lblTel;
	protected global::System.Web.UI.WebControls.Label lblOderID;


       
    }
}
