//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISRC.Web.T_Report {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtID;
		protected global::System.Web.UI.WebControls.TextBox txtCycle;
		protected global::System.Web.UI.WebControls.TextBox txtYear;
		protected global::System.Web.UI.WebControls.TextBox txtMonth;
		protected global::System.Web.UI.WebControls.TextBox txtQuarter;
		protected global::System.Web.UI.WebControls.TextBox txtSemiYear;
		protected global::System.Web.UI.WebControls.TextBox txtDeptID;
		protected global::System.Web.UI.WebControls.TextBox txtUserID;
		protected global::System.Web.UI.WebControls.TextBox txtFillDate;
		protected global::System.Web.UI.WebControls.TextBox txtDescription;
		protected global::System.Web.UI.WebControls.TextBox txtStatus;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
