//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISRC.Web.T_Report {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblCycle;
	protected global::System.Web.UI.WebControls.Label lblYear;
	protected global::System.Web.UI.WebControls.Label lblMonth;
	protected global::System.Web.UI.WebControls.Label lblQuarter;
	protected global::System.Web.UI.WebControls.Label lblSemiYear;
	protected global::System.Web.UI.WebControls.Label lblDeptID;
	protected global::System.Web.UI.WebControls.Label lblUserID;
	protected global::System.Web.UI.WebControls.Label lblFillDate;
	protected global::System.Web.UI.WebControls.Label lblDescription;
	protected global::System.Web.UI.WebControls.Label lblStatus;


       
    }
}
